---
- name: Configure MOTD banner
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Set MOTD banner
      ios_banner:
        banner: motd
        text: "{{ motd_message }}"
        state: present
      when: ansible_host == target_ip